### ISSUE TITLE
[v1.2.2] Modifying Identity to Account Map does not delete and recreate resource

### ISSUE THREAD

**Issue by h-wang94** [cyralinc/terraform-provider-cyral#119]
Note: This was discovered after trying to finding a manual fix described in https://github.com/cyralinc/terraform-provider-cyral/issues/118

## symptoms
- Updating an identity map (such as with updating the local account id) creates a new identity map but does not delete / modify the old identity map. Note: This might only be an issue for when the local account does not exist / shows a `_deleted`

Example terraform plan:
```
  # module.cyral_mysql_repository_turo_xyz_mysql_msvc.cyral_identity_map.this["admin-Engineering"] will be updated in-place
  ~ resource "cyral_identity_map" "this" {
        id                          = "<REDACTED>"
      ~ repository_local_account_id = "admin" -> "<REDACTED>"
        # (3 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }
```
In this terraform plan, the `repository_local_account_id` was modified / fixed to be the proper id, but what ends up happening is that the old identity map was not deleted or directly modified. 

What ends up happening is something that looks like this:
<img width="1537" alt="Screen Shot 2021-10-21 at 11 50 48 PM" src="https://user-images.githubusercontent.com/2381100/138406812-0484f769-a7fc-4424-bd4f-2e5ed45a376d.png">

## expected behavior
- When modifying an identity map, I expect that the identity map would either be modified directly or be recreated.

## affected version
- This was found and discovered using cyral provider v1.2.2

**Comment by wcmjunior** [comment]
Referenced internally by ticket `ENG-7170`.
