### ISSUE TITLE
[v1.2.2] Manually removing an identity map in the UI causes state refresh error whenever a Terraform plan is started

### ISSUE THREAD

**Issue by h-wang94** [cyralinc/terraform-provider-cyral#120]
## symptoms
- When an Identity to Account Map is manually removed from the UI and a Terraform plan is triggered, the Terraform plan errors when _refreshing the state_ of the associated identity to account map

The error message that Terraform throws out looks something like this:
```
...
...
<resource1>: Refreshing state... [id = <id1>]
<resource2>: Refreshing state... [id = <id2>]
<resource3>: Refreshing state... [id = <id3>]

Error: Unable to read integration. IntegrationID: 1v3ApyyPb6VzZGi79c1KSPfZTBL-my-local-account

error executing GET request; status code: 500; body: "{\"Message\":\"Rpc
error: code = Unknown desc = can't perform read because
repoID:\\\"<REPO_ID>\\\" identityType:END_USER
identityName:\\\"FakeUser\\\" repoAccountUUID:\\\"my-local-account\\\"
doesn't exist\"}\n"
```
Note that this happens while Terraform is syncing with the state.

As a result of this error, all subsequent Terraform plans cannot proceed.

To manually fix, the erroneous resource must be manually removed from the state so that Terraform does not know it needs to track the resource state.
```
terraform state rm '<RESOURCE_NAME>'
```

## expected behavior
- If an identity to account map is manually removed from the UI and a Terraform plan is triggered, then I would expect that the Terraform plan would detect, when refreshing the state, that the resource does not exist. As a result, Terraform would try to create the resource

## affected version
- This is discovered on cyral provider v1.2.2

**Comment by wcmjunior** [comment]
@h-wang94 , this bug was in the control plane API and the fix is available in `v2.25.2` and later versions.
