### ISSUE TITLE
Specify sidecar endpoint alias in cyral_sidecar resource

### ISSUE THREAD

**Issue by h-wang94** [cyralinc/terraform-provider-cyral#122]
In the UI sidecars page (`app/sidecars/<SIDECAR_ID`), we're able to specify an alias for the sidecar when we edit the settings
<img width="321" alt="Screen Shot 2021-10-27 at 1 26 19 PM" src="https://user-images.githubusercontent.com/2381100/139141811-108220f2-17b3-41fa-b1f5-90160d437c72.png">

It would be great if we could also specify this in the `cyral_sidecar` resource.

Version: 2.24.1

**Comment by wcmjunior** [comment]
Hi @h-wang94. Feature added in #132 and it will be released soon in provider version `> 2.2.1` which requires CP `>= 2.25`. Please reach out to Cyral support to upgrade the CP when the fix is available.
