### ISSUE TITLE
Deletion of data map attributes does not work

### ISSUE THREAD

**Issue by Yowgf** [cyralinc/terraform-provider-cyral#256]
## Setup

Initially, I have the following configuration. Cyral provider version is the main branch. Commit hash: `7c81d68f13f2d8c8e1d271fa982ab7369fd46a31`.

```terraform
resource "cyral_repository" "sqlserver1" {
    host = "localhost"
    port = 1433
    type = "sqlserver"
    name = "sqlserver1"
}

resource "cyral_repository_datamap" "sqlserver1" {
    repository_id = cyral_repository.sqlserver1.id
    mapping {
        label = "some-label"
        attributes = ["a.b.c", "b.c.d"]
    }
}
```

## Problem statement

Then, if I remove the attribute `b.c.d` from the data map:

```terraform
resource "cyral_repository_datamap" "sqlserver1" {
...
        attributes = ["a.b.c"] # Notice "b.c.d" is gone
    }
}
```

Hit `terraform apply`, the apply is successful. However, when I hit `terraform apply` again, the plan is the same as before the first apply, indicating that the apply didn't actually change the data map within the API. In fact, if I check the control plane UI, the data map was not update as I had expected.

**Comment by wcmjunior** [comment]
I believe setting `ForceNew` to `true` in the schema will fix this case.
