### ISSUE TITLE
[feature request] Add non-metadata "tags" as argument to cyral_policy

### ISSUE THREAD

**Issue by igaskin** [cyralinc/terraform-provider-cyral#427]
Currently, the [cyral_policy](https://registry.terraform.io/providers/cyralinc/cyral/latest/docs/resources/policy) resource includes an attribute called `tag` which is:
> Tags that can be used to organize and/or classify your policies

this `tag` is representative of the Policy.PolicyMetadata.Tags attribute in the `/policy` API, which is different than the Policy.Tags attribute.  

The scope of this request is to also support adding this top-level tag: https://cyral.com/docs/v4.7/policy/policy-structure/#structure-of-a-global-policy

> tags block: The optional [tags block](https://cyral.com/docs/v4.7/policy/policy-structure/#the-tags-block-of-a-policy) allows you to have this policy cover a set or sets of data labels. Each tag name listed here represents a set of data labels covered by this policy.

[API Reference](https://cyral.com/docs/v4.7/api-ref/)
![Screenshot 2023-07-27 at 5 10 52 PM](https://github.com/cyralinc/terraform-provider-cyral/assets/5673097/14c63212-8bf5-45bf-8872-a911536aa1b1)

**Comment by wcmjunior** [comment]
Hey @igaskin . We added support for the new attribute in our provider `v4.6.0`. Please refer to the [provider docs](https://registry.terraform.io/providers/cyralinc/cyral/latest/docs) for more information.
