### ISSUE TITLE
Document links

### ISSUE THREAD

**Issue by greenkiwi** [cyralinc/terraform-provider-cyral#71]
It would be really helpful to have links from the terraform documentation to the application documentation.

For example:
https://github.com/cyralinc/terraform-provider-cyral/blob/main/doc/resource_repository_conf_auth.md

Also, it would be great to have links to these settings to the docs.
https://cyral.com/docs/repo-advanced-settings

**Comment by wcmjunior** [comment]
We are currently working to standardize the provider documentation, but this is still an unfinished task. See: #59 .

**Comment by ptcar2009** [comment]
@greenkiwi I'm working on getting a standartized provider documentation so that it's compatible with the current documentation on terraform's own docs, will make the links available
