### ISSUE TITLE
Okta integration does not have SSO Outputs

### ISSUE THREAD

**Issue by greenkiwi** [cyralinc/terraform-provider-cyral#76]
It would be great if the okta integration had outputs that mapped to the URLs and information available in the UI.  This could then be consumed by other TF to make use of the integration directly without having to copy and paste from the UI.

https://github.com/cyralinc/terraform-provider-cyral/blob/main/doc/resource_integration_okta.md

![image](https://user-images.githubusercontent.com/54169/124746167-ac9b6e80-df74-11eb-9ec5-7dbb281a6a6b.png)

**Comment by wcmjunior** [comment]
@greenkiwi , have you seen this module? https://github.com/cyralinc/terraform-cyral-idp-okta/
Is this what you are looking for?

**Comment by greenkiwi** [comment]
@wcmjunior Yes and no.  I think that having the module is awesome.  

That being said, I think that the endpoints should be `Attributes Reference` on the `cyral_okta` resource rather than having to pull them from data and/or generate them via special knowledge in locals.   This might mean that the TF mapping to the API needs to create the object and then poll to fetch the information once the object has been fully created, assuming something happens asynchronously.

![image](https://user-images.githubusercontent.com/54169/124996470-144cd900-e09d-11eb-82d6-f7ec906c4b12.png)

Similarly, in that module - I think that you don't need to use the `data.okta_app_metadata_saml` as it's all available from the [okta_app_saml attribute reference](https://registry.terraform.io/providers/okta/okta/latest/docs/resources/app_saml#attributes-reference)

**Comment by wcmjunior** [comment]
Closing this ticket as we are deprecating the vendor-specific integrations and focusing only on the generic SAML from `terraform-provider-cyral:v4.2.0` and CP `v4.6.0` onwards.
