### ISSUE TITLE
Support for managing the SSO group <> Role mapping 

### ISSUE THREAD

**Issue by greenkiwi** [cyralinc/terraform-provider-cyral#77]
It would be great to support managing the configuration of SSO groups to roles.

![image](https://user-images.githubusercontent.com/54169/124755205-30f2ef00-df7f-11eb-81f4-92e7a50162fd.png)

We would likely need to have support for `Roles` as well and some mechanism for updating the maps for the built-in roles.

**Comment by wcmjunior** [comment]
Enhancement will be referred internally by Cyral team as `ENG-5835`.
