### ISSUE TITLE
Terraform registry does not show docs for provider 

### ISSUE THREAD

**Issue by greenkiwi** [cyralinc/terraform-provider-cyral#78]
It appears that the docs are not consistent with the guidelines and as such are not showing up in the hashicorp registry.

https://www.terraform.io/docs/registry/providers/docs.html

It also appears that you can use [tfplugindocs](https://github.com/hashicorp/terraform-plugin-docs) to help generate the docs, if that helps.

See:
https://registry.terraform.io/providers/cyralinc/cyral/latest
![image](https://user-images.githubusercontent.com/54169/124854417-6806e600-dffb-11eb-95ba-5410c84da98f.png)

**Comment by wcmjunior** [comment]
@ptcar2009 , please also address this one in #59.
