### ISSUE TITLE
Attributes for the cyral_sidecar resource are flat

### ISSUE THREAD

**Issue by greenkiwi** [cyralinc/terraform-provider-cyral#79]
The `Variables` which are actually `Argument Reference` in provider nomenclature have the properties for the `aws_configuration` object flattened into the top-level variables.

See: https://github.com/cyralinc/terraform-provider-cyral/blob/main/doc/resource_sidecar.md

Hopefully, all of this can be generated from the go resource objects directly and that will put them in the right format.

**Comment by wcmjunior** [comment]
We are refactoring docs to follow Terraform standards, so it should be fixed after #59 is merged.
