### ISSUE TITLE
Omitting access_duration in cyral_identity_map results in plan change on every plan

### ISSUE THREAD

**Issue by h-wang94** [cyralinc/terraform-provider-cyral#81]
Link to doc: https://github.com/cyralinc/terraform-provider-cyral/blob/main/doc/resource_identity_map.md

Even though it says that `access_duration` can be omitted, after an `identity_map` has been created, any subsequent terraform plan results in a change. Nothing ends up happening after applying, but these changes show up in every plan thereafter.

```
  ~ resource "cyral_identity_map" "identity_map" {
        id                          = "1v3ApyyPb6VzZGi79c1KSPfZTBL-my-local-account"
        # (4 unchanged attributes hidden)

      - access_duration {
          - days    = 0 -> null
          - hours   = 0 -> null
          - minutes = 0 -> null
          - seconds = 0 -> null
        }
    }
```

I would assume that if the docs specify that its not required, then if its omitted when creating the resource, it shouldn't result in this change on any subsequent plans.

It feels like theres probably some error of not setting this block in the TF state by default if its omitted:
```
      access_duration {
          days    = 0 -> null
          hours   = 0 -> null
          minutes = 0 -> null
          seconds = 0 -> null
       }
```

As a separate, but related question:
its not super clear if setting 
```
    access_duration {
        days    = 0
        hours   = 0
        minutes = 0
        seconds = 0
    }
```
is equivalent to omitting it.

**Comment by wcmjunior** [comment]
@h-wang94 and @greenkiwi , please refer to `v2.0.1` for this bug fix. Make sure to read the change log to check the minimum CP version required for this version.
